# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRScanner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QRScanner
  pod 'Firebase/Core'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionBarcodeModel'

  target 'QRScannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QRScannerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
